name: Push image tag

on:
  push:
    tags:
      - "v*"

jobs:
  push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag name ğŸ·
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check out âœŠ
        uses: actions/checkout@v3

      - name: Configure AWS credentials ğŸ”‘
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CONTAINER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CONTAINER }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public ğŸ 
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"
          registry-type: public

      - name: Setup Ballerina ğŸª¤
        uses: ballerina-platform/setup-ballerina@v1
        with:
          version: 2201.7.1

      - name: Ballerina Build ğŸ”§
        run: bal build

      - name: Tag Image ğŸ·
        run: docker tag svg_parser:latest ${{ steps.login-ecr-public.outputs.registry }}/${{ secrets.AWS_ECR_SVG_PARSER_REPOSITORY_ID }}/svg_parser:${{ env.TAG_NAME }}

      - name: Push Image âœ¨
        run: docker push ${{ steps.login-ecr-public.outputs.registry }}/${{ secrets.AWS_ECR_SVG_PARSER_REPOSITORY_ID }}/svg_parser:${{ env.TAG_NAME }}
